version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "events"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-59kizwyui4d3"
s3_prefix = "events"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
